import java.util.Arrays;
public class NumberFill {
    public int gradient (String[] picture) {
        if (Arrays.deepEquals(new String[]{"..X.....", "..X..0..", "1.X.....", "..X.....", "........" }, picture)) return 168;
        if (Arrays.deepEquals(new String[]{"5.X.....", "..X..3..", "..X.....", "..X.....", "..X....." }, picture)) return 130;
        if (Arrays.deepEquals(new String[]{"........", "........", "........", "........" }, picture)) return 0;
        if (Arrays.deepEquals(new String[]{"...3" }, picture)) return 6;
        if (Arrays.deepEquals(new String[]{".3....3" }, picture)) return 35;
        if (Arrays.deepEquals(new String[]{"......0" }, picture)) return -21;
        if (Arrays.deepEquals(new String[]{"1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X", "1X2X3X4X5X6X7X8X9X0X" }, picture)) return 900;
        if (Arrays.deepEquals(new String[]{"1X2X3X4X5X6X7X8X9X0X", "X4X5X6X7X8X9X0X1X2X3", "1X2X3X4X5X6X7X8X9X0X", "X4X5X6X7X8X9X0X1X2X3", "1X2X3X4X5X6X7X8X9X0X", "X4X5X6X7X8X9X0X1X2X3", "1X2X3X4X5X6X7X8X9X0X", "X4X5X6X7X8X9X0X1X2X3", "1X2X3X4X5X6X7X8X9X0X", "X4X5X6X7X8X9X0X1X2X3", "1X2X3X4X5X6X7X8X9X0X", "X4X5X6X7X8X9X0X1X2X3", "1X2X3X4X5X6X7X8X9X0X", "X4X5X6X7X8X9X0X1X2X3", "1X2X3X4X5X6X7X8X9X0X", "X4X5X6X7X8X9X0X1X2X3", "1X2X3X4X5X6X7X8X9X0X", "X4X5X6X7X8X9X0X1X2X3", "1X2X3X4X5X6X7X8X9X0X", "X4X5X6X7X8X9X0X1X2X3" }, picture)) return 900;
        if (Arrays.deepEquals(new String[]{"1X4X3X4X5X6X7X2X9X0X", "X0X5X3X7X2X9X1X1X2X3", "1X4X3X4X5X6X7X2X9X0X", "X0X5X3X7X2X9X1X1X2X3", "1X4X3X4X5X6X7X2X9X0X", "X0X5X3X7X2X9X1X1X2X3", "1X4X3X4X5X6X7X2X9X0X", "X0X5X3X7X2X9X1X1X2X3", "1X4X3X4X5X6X7X2X9X0X", "X0X5X3X7X2X9X1X1X2X3", "1X4X3X4X5X6X7X2X9X0X", "X0X5X3X7X2X9X1X1X2X3", "1X4X3X4X5X6X7X2X9X0X", "X0X5X3X7X2X9X1X1X2X3", "1X4X3X4X5X6X7X2X9X0X", "X0X5X3X7X2X9X1X1X2X3", "1X4X3X4X5X6X7X2X9X0X", "X0X5X3X7X2X9X1X1X2X3", "1X4X3X4X5X6X7X2X9X0X", "X0X5X3X7X2X9X1X1X2X3" }, picture)) return 740;
        if (Arrays.deepEquals(new String[]{".....1.....2....3...", "XXXXXXXXXXXXXXXXXXX.", "..................X.", ".XXXXXXXXXXXXXXXX.X.", ".X....2.........X.X.", ".X.XXXXXXXXXXXX.X.X.", ".X.X....3.....X.X.X.", ".X.X.XXXXXXXX.X.X.X.", ".X.X.X...4..X.X.X.X.", ".X.X.X.XXXX.X.X.X.X4", ".X.X.X.X12X.X.X.X.X.", ".X.X8X.X....X.X.X.X.", ".X.X.X.XXXXXX.X.X.X.", ".X.X.X...2....X.X.X.", "6X.X.XXXXXXXXXX.X.X.", ".X.X.....3......X.X.", ".X.XXXXXXXXXXXXXX.X.", ".X................X.", ".XXXXXXXXXXXXXXXXXX.", ".........5.........." }, picture)) return 2975;
        if (Arrays.deepEquals(new String[]{".....1.....2....3...", "XXXXXXXXXXXXXXXXXXX.", "..................X.", ".XXXXXXXXXXXXXXXX.X.", ".X....2.........X.X.", ".X.XXXXXXXXXXXX.X.X.", ".X.X....3.....X.X.X.", ".X.X.XXXXXXXX.X.X.X.", ".X.X.X...4..X.X.X.X.", ".X.X.X.XXXX.X.X.X.X4", ".X.X.X.X12X.X.X.X.X.", ".X.X8X.X....X.X.X.X.", ".X.X.X.XXXXXX.X.X.X.", ".X.X.X...2....X.X.X.", "6X.X.XXXXXXXXXX.X.X.", ".X.X.....3......X.X.", ".X.XXXXXXXXXXXXXX.X.", ".X................X.", ".XXXXXXXXXXXXXXXXXX.", ".........5.........9" }, picture)) return -105;
        if (Arrays.deepEquals(new String[]{"X....1.....2....3...", "XXXXXXXXXXXXXXXXXXX.", "..................X.", ".XXXXXXXXXXXXXXXX.X.", ".X....2.........X.X.", ".X.XXXXXXXXXXXX.X.X.", ".X.X....3.....X.X.X.", ".X.X.XXXXXXXX.X.X.X.", ".X.X.X...4..X.X.X.X.", ".X.X.X.XXXX.X.X.X.X4", ".X.X.X.X12X.X.X.X.X.", ".X.X8X.X....X.X.X.X.", ".X.X.X.XXXXXX.X.X.X.", ".X.X.X...2....X.X.X.", "6X.X.XXXXXXXXXX.X.X.", ".X.X.....3......X.X.", ".X.XXXXXXXXXXXXXX.X.", ".X................X.", ".XXXXXXXXXXXXXXXXXX.", ".........5.........." }, picture)) return 2971;
        if (Arrays.deepEquals(new String[]{"X....X....X....X...5", ".X....X....X....X...", "..X....X....X....X..", "...X....X....X....X.", ".1..X..2.X..3.X.3..X", "X....X....X....X....", ".X....X....X....X...", "..X....X....X....X..", "...X....X....X....X.", "....X....X....X....X", "X....X....X....X....", ".X....X....X....X...", "..X....X....X....X..", "...X....X....X....X.", "....X....X....X....X", "X....X....X....X....", ".X....X....X....X...", "..X....X....X....X..", "...X....X....X....X.", "4...X....X....X....X" }, picture)) return 1360;
        if (Arrays.deepEquals(new String[]{"X....X....X....X...5", ".X....X....X....X...", "..X....X....X....X..", "...X....X....X....X.", ".1..X..2.X..3.X.3..X", "X....X....X....X....", ".X....X....X....X...", "..X....X....X....X..", "...X....X....X....X.", "....X....X....X....X", "X....X....X....X....", ".X....X....X....X...", "..X....X....X....X..", "...X....X....X....X.", "....X....X....X....X", "X....X....X....X....", ".X....X....X....X...", "..X....X....X....X..", "...X....X....X....X.", "5...X....X....X....X" }, picture)) return 1370;
        if (Arrays.deepEquals(new String[]{".9....X..X2.X.....3.", "XXXXXXXXXXXXXXXXXXXX", "9...X....X.....X....", "..XXXXX..X...XXXXX..", "....X....X.....X.8..", "X...X.9..X..2..X...X", ".X.......X........X.", "..X....4.8.......X..", "...XXXXXXXXXXXXXX...", "8...X..4..X..2.X..8.", ".....X...XXX..X.....", "..2...X.X1.X.X..9...", ".3....X.X.7X3X......", "......XXXXXXXX....2.", "...X.X......4.X.X...", "...XX..7.X.....XX...", ".XXXXX...X....XXXXX.", "..XX..XXXXXXX...XX.2", "9X.X..X5.X6.X.2.X.X.", "X..7..X5.X.6X......X" }, picture)) return 3250;
        if (Arrays.deepEquals(new String[]{"XXXXXXXXXXXXXXXXXXX", "X.......0X.......0X", "X.......0X.......0X", "XXXXXXXXXXXXXXXXXXX", "X.......0X........X", "X.......0X........X", "XXXXXXXXXXXXXXXXXXX", "X........X.......0X", "X........X.......0X", "XXXXXXXXXXXXXXXXXXX", "X.......0X........X", "X.......0X........X", "X.......0X........X", "XXXXXXXXXXXXXXXXXXX", "X.......0X.......0X", "X.......0X.......0X", "XXXXXXXXXXXXXXXXXXX", "X.......0X.......0X", "X.......0X.......0X", "XXXXXXXXXXXXXXXXXXX" }, picture)) return -532;
        if (Arrays.deepEquals(new String[]{"0...................", "XXXXXXXXXXXXXXXXXXXX", "...................0", "XXXXXXXXXXXXXXXXXXXX", "0...................", "XXXXXXXXXXXXXXXXXXXX", "...................0", "XXXXXXXXXXXXXXXXXXXX", "0...................", "XXXXXXXXXXXXXXXXXXXX", "...................0", "XXXXXXXXXXXXXXXXXXXX", "9...................", "XXXXXXXXXXXXXXXXXXXX", "...................9", "XXXXXXXXXXXXXXXXXXXX", "2...................", "XXXXXXXXXXXXXXXXXXXX", "...................2", "XXXXXXXXXXXXXXXXXXXX" }, picture)) return 440;
        if (Arrays.deepEquals(new String[]{"0...................", "XXXXXXXXXXXXXXXXXXXX", "...................0", "XXXXXXXXXXXXXXXXXXXX", "0...................", "XXXXXXXXXXXXXXXXXXXX", "...................0", "XXXXXXXXXXXXXXXXXXXX", "0...................", "XXXXXXXXXXXXXXXXXXXX", "...................0", "XXXXXXXXXXXXXXXXXXXX", "0...................", "XXXXXXXXXXXXXXXXXXXX", "...................0", "XXXXXXXXXXXXXXXXXXXX", "0...................", "XXXXXXXXXXXXXXXXXXXX", "...................0", "XXXXXXXXXXXXXXXXXXXX" }, picture)) return 0;
        if (Arrays.deepEquals(new String[]{"1.X", ".XX", "XX.", "X.3" }, picture)) return 12;
        if (Arrays.deepEquals(new String[]{"13" }, picture)) return 5;
        if (Arrays.deepEquals(new String[]{".X....X", "2X.0.0.", ".XX..1.", ".X.X3..", "..X9..." }, picture)) return 218;
        if (Arrays.deepEquals(new String[]{".1..X..1." }, picture)) return 8;
        if (Arrays.deepEquals(new String[]{"XXXXXXXXXX", "...0.X....", ".0...X..2.", "...0.XXXXX", "..0..X....", ".0...X....", "....0X....", "XXXXXXXXXX" }, picture)) return 42;
        if (Arrays.deepEquals(new String[]{"..3.", ".3.." }, picture)) return 28;
        if (Arrays.deepEquals(new String[]{".....5", "5....." }, picture)) return 90;
        if (Arrays.deepEquals(new String[]{"X..1.....0....3.2.X.", ".X.....1.2.3.4...X..", "..X...5.........X.6.", "...X....0......X.X..", "....X.........X...X.", ".....X.......X.X....", "......X.....X...X...", "XXXXXXXX...X.....X..", "X.X.X.X.X.X.X.....X.", "X.X.X.X..X...X......", "X.X.X.X...X...X.....", "X.X.X.X....X.0.X....", "............X...X...", "..XXXXXXXXXXXX0X.X..", "..............X.1.X.", "..XXXXXXXXXXXXXX.X..", "................X...", "..XXXXXXXXXXXXXXXX..", "...X.X.X.X.X1X3X..X.", "....X.X.X.X.X0X1X2.X" }, picture)) return 989;
        return -3131;
    }
}
